### ISSUE TITLE
Make app FLOSS

### ISSUE THREAD

**Issue by rugk** [YTVanced/VancedWebsite#10]
It would be great if you could release the app itself as [free/libre open-source software](https://en.wikipedia.org/wiki/Free_and_open-source_software).

As far as I see only some installer and the website is open-source.

**Comment by MrDodojo** [comment]
That would mean Google knows what code we use to change the app and that means instant goodbye to Vanced.

**Comment by KevinX8** [comment]
> It would be great if you could release the app itself as [free/libre open-source software](https://en.wikipedia.org/wiki/Free_and_open-source_software).
> 
> As far as I see only some installer and the website is open-source.

You must realise the app is a mod of stock YouTube right? Where do you think we would be able to get the YouTube source code from lol.

**Comment by rugk** [comment]
Ah okay, this was the catch then. We'll then it's a copyright violation anyway, … Then you cannot release that as FLOSS, very obviously.
