### ISSUE TITLE
App doesn't detect internet connection

### ISSUE THREAD

**Issue by schwarcu** [YTVanced/VancedWebsite#16]
It stopped working yesterday I think.
Reinstallation of both vanced app and micro G doesn't solve the problem.
![Screenshot_20200626_174923_com vanced android youtube](https://user-images.githubusercontent.com/31127747/85876271-c472db00-b7d5-11ea-87db-c55b5502a951.jpg)

**Comment by MrDodojo** [comment]
This GitHub page isn't the place to place YouTube Vanced issues, heck, the app isn't even opensource so it isn't anywhere to be found here either.

**Comment by schwarcu** [comment]
@MrDodojo  where should I report it then?
