### ISSUE TITLE
[bug] dark theme glitch

### ISSUE THREAD

**Issue by agentjill** [YTVanced/VancedWebsite#22]
When dark theme is activated when a video is playing in background the settings page only will be in dark theme with text still in black colour. The dark theme is only applies correctly when there is no video playing in background.

**Comment by VancedOfficial** [comment]
Please report in the correct repository if you haven't already (https://github.com/YTVanced/Vanced). Though the dark theme comes from Google so please do check if Official youtube has the same problem (with the same exact version).
