### ISSUE TITLE
I found crash

### ISSUE THREAD

**Issue by annybang** [YTVanced/VancedWebsite#23]
I found it on note20. Android 10

Crash in event log:
06-09 16:34:09.978  1000  1097  3705 I am_crash: [28063,0,com.vanced.android.youtube,821804612,java.lang.SecurityException,Failed to find provider com.mgoogle.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority,Parcel.java,2088]

06-09 16:34:09.977 10338 28063 28063 E AndroidRuntime: FATAL EXCEPTION: main
06-09 16:34:09.977 10338 28063 28063 E AndroidRuntime: Process: com.vanced.android.youtube, PID: 28063
06-09 16:34:09.977 10338 28063 28063 E AndroidRuntime: java.lang.SecurityException: Failed to find provider com.mgoogle.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
06-09 16:34:09.977 10338 28063 28063 E AndroidRuntime:    at android.os.Parcel.createException(Parcel.java:2088)

**Comment by VenNeptury** [comment]
This is not the right place for this, please join one of our socials and report it there
