### ISSUE TITLE
Prefered video speed not working

### ISSUE THREAD

**Issue by Viproz** [YTVanced/VancedWebsite#9]
Hi,

I couldn't find a place for bug reports about the application so I'm posting here.

I updated to the last version but now the prefered video speed does not work, I expect it to change the default speed value of all the video I open to the selected value (as it did in previous versions) but it simply doesn't do it, it opens video at normal speed.

Version used: 15.05.54 - Build 01.41.10
Android 9 with MIUI

Thanks for the app!

**Comment by KevinX8** [comment]
Bug reports for the app go in the Discord, read info for more details
